name: Freeze
version: 1.4.2
description: Freeze players.
author: aurel2108
website: http://aurel2108.eu
main: me.aurel2108.freeze.Freeze
commands:
 freeze:
  description: Freeze or unfreeze a player.
  usage: Correct usage is /freeze <player name> [players...] [reason]
  permission: freeze.freeze
 tmpfreeze:
  description: Temporarily freeze a player.
  usage: Correct usage is /tmpfreeze <player name> <seconds> [reason]
  permission: freeze.tmpfreeze
 freezeall:
  description: Freeze or unfreeze every players.
  usage: Correct usage is /freezeall [world] [reason] ([world] can be "all" for freeze all worlds)
  permission: freeze.freezeall
 unfreezeall:
  description: Unfreeze every players.
  usage: Correct usage is /unfreezeall
  permission: freeze.unfreezeall
 rldfreeze:
  description: Reload the plugin and it's config
  usage: Correct usage is /rldfreeze
  permission: freeze.reload
 freezelist:
  description: List all the freezed or tmpfreezed players.
  usage: Correct usage is /freezelist
  permission: freeze.list
 freezecheck:
  description: Update the plugin.
  usage: Correct usage is /freezecheck
  permission: freeze.checkupdate
permissions:
 freeze.*:
  description: Be able to use all commands.
  children:
    freeze.freeze: true
    freeze.freezeall: true
    freeze.unfreezeall: true
    freeze.tmpfreeze: true
    freeze.reload: true
    freeze.list: true
    freeze.checkupdate: true
 freeze.freeze:
  description: Be able to freeze players.
  default: op
 freeze.tmpfreeze:
  description: Be able to temporarily freeze players.
  default: op
 freeze.freezeall:
  description: Be able to freeze every players.
  default: op
 freeze.unfreezeall:
  description: Be able to unfreeze every players.
  default: op
 freeze.reload:
  description: Be able to reload the plugin and it's config
  default: op
 freeze.never:
  description: Never be freezed.
  default: op
 freeze.list:
  description: Be able to list every freezed or tmpfreezed players.
  default: op
 freeze.checkupdate:
  description: Be able to see when a new update for the plugin is available
  default: op